services:
  backend:
    build: ./backend 
    ports:
      - "3001:3001" 
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/translations

    depends_on:
      - translator
      - db
    networks:
      - my-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: translations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data  
      - /db:/docker-entrypoint-initdb.d/
    networks:
      - my-network

  frontend:
    build: ./frontend 
    ports:
      - "8080:80" 
    networks:
      - my-network
    depends_on:
      - db

  translator:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:

networks:
  my-network:
    