---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-password
  namespace: default
spec:
  encryptedData:
    password: AgAcm1D/tHRDrEhxfwSRRVB5EosQRTCoNCOPpvAz3bbVBXrD7Av5vjZNV4iqosLGfceHLvzky/y0ngGDVYWbKkr5irbc8UJbWMaV2dpNWv8hlX7xN04hd5y2//5jU2am6scch7MM8qHbnBHt0P5TtW5S49E4aCY6zcE+LTaWrlk2Y8lorZzpS05qFNjQYgZeF4tnzffy5EsCVHC4/Z+LVBl7XTLZngxN7F2DBC0KtM2SN/WpOMPsSF94lYMfm4hBGDAkl8hXCroTaj9NNTXFHR97l7Sc6jWhmFqpav3EQ/TpAz6SZdQthkJToerNMfBWS93vlEw+SV3BfD5LErrYtBZ4x7KNY2altPTrxIrY71T2OiI33mu2JK/h+GL35Y17WoyhBugHPl7otT/uZPq5h2Xh0kvhich5YlKGPFeG0gLRCLNWBvUST7n3EiODEqh5q/PgrR8Q1/4fFE4xKuoyzZbqBcWVYEoWToaxYGDCGhhH6psT8lMHDbicUSgJVhOIWqBU9EHf3K4mIoRZqHsiBcttVtC7kKINR8XoVsNKz5Zchsie7vcWqk1vuEkEqqDCJEIvBnMceGSjRDn5E1O91F1xpcygo2BnQwCbdulhqr7Bb2GXeMcZ/amR3iNO5Yezj3nB2c9RBgWrrEgzcRfwByoXhM9e6LAj9hNGg5dzHR0XdRwtbH8+/s4c/dpq88PFI+9Xm9Le2dQhEIViZg==
  template:
    metadata:
      name: postgres-password
      namespace: default
