apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Helm הופך את הסיסמה ל-base64 באופן אוטומטי
  POSTGRES_PASSWORD: {{ .Values.database.auth.postgresPassword | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_DB: {{ .Values.database.auth.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.database.auth.postgresUser | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS translations (
      id SERIAL PRIMARY KEY,
      source_text TEXT NOT NULL,
      target_lang VARCHAR(10) NOT NULL,
      translated_text TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT now()
    );