global:
  domain: translator.local

backend:
  image: tamilevkovitz/image-backend
  replicaCount: 2
  port: 3001
  env:
    databaseUrl: "postgres://postgres:postgres@postgres-service:5432/translations"
    translatorHost: "translator-service"
  
frontend:
  image: tamilevkovitz/frontend
  replicaCount: 2
  port: 80

translator:
  image: libretranslate/libretranslate:latest
  replicaCount: 1
  port: 5000
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"


database:
  name: translations
  user: postgres
  password: cG9zdGdyZXM=
  storage: 10Gi
  replicaCount: 1
  image: postgres:15-alpine
  
ingress:
  enabled: true
  host: translator.local
  

volume:
  data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS translations (
      id SERIAL PRIMARY KEY,
      source_text TEXT NOT NULL,
      target_lang VARCHAR(10) NOT NULL,
      translated_text TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT now()
    );