# Global Settings
global:
  domain: translator.local

# Frontend
frontend:
  replicaCount: 2
  image: tamilevkovitz/frontend
  imagePullPolicy: Never
  service:
    name: frontend-service
    port: 80

# Backend
backend:
  replicaCount: 2
  image: tamilevkovitz/image-backend
  imagePullPolicy: Never
  service:
    name: backend-service
    port: 3001
  env:
    databaseUrl: "postgres://postgres:postgres@postgres-service:5432/translations"
    translatorHost: "translator-service"

# Database (PostgreSQL)
database:
  replicaCount: 1
  image: postgres:15-alpine
  imagePullPolicy: Never
  auth:
    postgresDb: "translations"
    postgresUser: "postgres"
    postgresPassword: "postgres" # Helm יהפוך את זה ל-base64 בעצמו ב-Template
  persistence:
    size: 10Gi
  service:
    name: postgres-service
    port: 5432

# Translator (LibreTranslate)
translator:
  replicaCount: 1
  image: libretranslate/libretranslate:latest
  imagePullPolicy: IfNotPresent
  service:
    name: translator-service
    port: 5000

# Ingress
ingress:
  enabled: true
  name: app-translator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"